"use client";

import { useCallback, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { useAuth } from "@/components/auth-provider";
import { LoadingPanel } from "@/components/loading-panel";
import { InlineError, PortalHeading } from "@/components/portal-ui";
import { PrescriptionItemsView, PrescriptionStatusBadge } from "@/components/prescription-ui";
import { ProtectedRoute } from "@/components/protected-route";
import { cancelPrescription, getDoctorPrescription, issuePrescription, updatePrescriptionDraft } from "@/lib/api";
import type { DoctorPrescription, PrescriptionDraftInput, PrescriptionItemInput } from "@/types/prescriptions";

const emptyItem = (): PrescriptionItemInput => ({ medicineName: "", strength: "", medicineForm: "", dosage: "", frequency: "", duration: "", quantity: "", route: "", instructions: "" });

function Content() {
  const { prescriptionId } = useParams<{ prescriptionId: string }>(); const { session } = useAuth();
  const [value, setValue] = useState<DoctorPrescription | null>(null); const [form, setForm] = useState<PrescriptionDraftInput>({ validityDays: 30, generalInstructions: "", items: [] });
  const [busy, setBusy] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const apply = useCallback((next: DoctorPrescription) => { setValue(next); setForm({ validityDays: next.validityDays, generalInstructions: next.generalInstructions ?? "", items: next.items.map((item) => ({ medicineName: item.medicineName, strength: item.strength, medicineForm: item.medicineForm, dosage: item.dosage, frequency: item.frequency, duration: item.duration, quantity: item.quantity, route: item.route, instructions: item.instructions })) }); }, []);
  const load = useCallback(async () => { if (!session) return; try { apply(await getDoctorPrescription(session.access_token, prescriptionId)); } catch (e) { setError(e instanceof Error ? e.message : "The prescription could not be loaded."); } }, [apply, prescriptionId, session]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  function change(index: number, field: keyof PrescriptionItemInput, text: string) { setForm((current) => ({ ...current, items: current.items.map((item, i) => i === index ? { ...item, [field]: text } : item) })); }
  async function save() { if (!session) return; setBusy("save"); setError(null); setNotice(null); try { apply(await updatePrescriptionDraft(session.access_token, prescriptionId, form)); setNotice("Draft saved."); } catch (e) { setError(e instanceof Error ? e.message : "The draft could not be saved."); } finally { setBusy(null); } }
  async function issue() { if (!session || !window.confirm("Issue this prescription? It will become immutable.")) return; setBusy("issue"); setError(null); try { apply(await issuePrescription(session.access_token, prescriptionId)); setNotice("Prescription issued securely."); } catch (e) { setError(e instanceof Error ? e.message : "The prescription could not be issued."); } finally { setBusy(null); } }
  async function cancel() { if (!session) return; const reason = window.prompt("Cancellation reason (required, at least 3 characters):"); if (!reason) return; setBusy("cancel"); setError(null); try { apply(await cancelPrescription(session.access_token, prescriptionId, reason)); setNotice("Prescription cancelled and its QR revoked."); } catch (e) { setError(e instanceof Error ? e.message : "The prescription could not be cancelled."); } finally { setBusy(null); } }
  if (!value && !error) return <LoadingPanel label="Loading prescription editor..." />;
  return <main className="mx-auto max-w-5xl px-6 py-10 lg:px-8 lg:py-14"><PortalHeading eyebrow="Doctor prescription" title={value ? `Prescription for ${value.patientName}` : "Prescription"} description="Create structured medication instructions and issue them when the consultation permits." backHref="/doctor/prescriptions" backLabel="Back to prescriptions" />
    <div className="mt-7 space-y-3"><InlineError message={error} />{notice ? <p className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900">{notice}</p> : null}</div>{value ? <>
      <div className="mt-8"><PrescriptionStatusBadge status={value.status} expired={value.expired} /></div>
      {value.status === "DRAFT" ? <section className="mt-6 space-y-5 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8">
        <label className="block text-sm font-medium">Validity (days)<input className="mt-2 block w-full rounded-xl border border-slate-300 px-4 py-3" min={1} max={90} type="number" value={form.validityDays} onChange={(e) => setForm({ ...form, validityDays: Number(e.target.value) })} /></label>
        <label className="block text-sm font-medium">General instructions<textarea className="mt-2 min-h-28 w-full rounded-xl border border-slate-300 px-4 py-3" maxLength={5000} value={form.generalInstructions} onChange={(e) => setForm({ ...form, generalInstructions: e.target.value })} /></label>
        <div className="flex items-center justify-between"><h2 className="text-xl font-semibold">Medicines ({form.items.length}/20)</h2><button className="rounded-xl border border-teal-700 px-4 py-2 text-sm font-semibold text-teal-800 disabled:opacity-50" disabled={form.items.length >= 20 || busy !== null} onClick={() => setForm({ ...form, items: [...form.items, emptyItem()] })}>Add medicine</button></div>
        {form.items.map((item, index) => <fieldset className="grid gap-4 rounded-2xl border border-slate-200 p-5 sm:grid-cols-2" key={index}><legend className="px-2 font-semibold">Medicine {index + 1}</legend>{(["medicineName", "strength", "medicineForm", "dosage", "frequency", "duration", "quantity", "route"] as const).map((field) => <label className="text-sm font-medium capitalize" key={field}>{field.replace(/([A-Z])/g, " $1")}<input required={["medicineName", "dosage", "frequency", "duration"].includes(field)} className="mt-1 block w-full rounded-xl border border-slate-300 px-3 py-2" value={item[field] ?? ""} onChange={(e) => change(index, field, e.target.value)} /></label>)}<label className="text-sm font-medium sm:col-span-2">Instructions<textarea className="mt-1 min-h-20 w-full rounded-xl border border-slate-300 px-3 py-2" value={item.instructions ?? ""} onChange={(e) => change(index, "instructions", e.target.value)} /></label><button className="justify-self-start text-sm font-semibold text-rose-700" onClick={() => setForm({ ...form, items: form.items.filter((_, i) => i !== index) })}>Remove</button></fieldset>)}
        <div className="flex flex-wrap gap-3"><button className="rounded-xl border border-slate-300 px-5 py-3 text-sm font-semibold disabled:opacity-50" disabled={busy !== null} onClick={() => void save()}>{busy === "save" ? "Saving..." : "Save draft"}</button><button className="rounded-xl bg-teal-700 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50" disabled={busy !== null || form.items.length === 0} onClick={() => void issue()}>{busy === "issue" ? "Issuing..." : "Issue prescription"}</button></div>
      </section> : <><section className="mt-8"><PrescriptionItemsView items={value.items} /></section>{value.generalInstructions ? <p className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 whitespace-pre-wrap">{value.generalInstructions}</p> : null}{value.status === "ISSUED" ? <button className="mt-6 rounded-xl bg-rose-700 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50" disabled={busy !== null} onClick={() => void cancel()}>{busy === "cancel" ? "Cancelling..." : "Cancel prescription"}</button> : <section className="mt-6 rounded-2xl border border-rose-200 bg-rose-50 p-5 text-rose-950"><h2 className="font-semibold">Cancelled</h2><p className="mt-2 whitespace-pre-wrap text-sm">{value.cancellationReason}</p></section>}</>}
    </> : null}</main>;
}
export default function Page() { return <ProtectedRoute roles={["DOCTOR"]}><Content /></ProtectedRoute>; }
